// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/numbering_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "github.com/edy4c7/works-uploader/internal/entities"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockNumberingRepository is a mock of NumberingRepository interface
type MockNumberingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNumberingRepositoryMockRecorder
}

// MockNumberingRepositoryMockRecorder is the mock recorder for MockNumberingRepository
type MockNumberingRepositoryMockRecorder struct {
	mock *MockNumberingRepository
}

// NewMockNumberingRepository creates a new mock instance
func NewMockNumberingRepository(ctrl *gomock.Controller) *MockNumberingRepository {
	mock := &MockNumberingRepository{ctrl: ctrl}
	mock.recorder = &MockNumberingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNumberingRepository) EXPECT() *MockNumberingRepositoryMockRecorder {
	return m.recorder
}

// FindByType mocks base method
func (m *MockNumberingRepository) FindByType(ctx context.Context, typ int) (*entities.Numbering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByType", ctx, typ)
	ret0, _ := ret[0].(*entities.Numbering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByType indicates an expected call of FindByType
func (mr *MockNumberingRepositoryMockRecorder) FindByType(ctx, typ interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByType", reflect.TypeOf((*MockNumberingRepository)(nil).FindByType), ctx, typ)
}

// Save mocks base method
func (m *MockNumberingRepository) Save(ctx context.Context, e *entities.Numbering) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockNumberingRepositoryMockRecorder) Save(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockNumberingRepository)(nil).Save), ctx, e)
}
